services:
    # Form services
    drsoft_fr.module.validate_customer_pro.form.data_provider.setting_form_data_provider:
        class: DrSoftFr\Module\ValidateCustomerPro\Form\DataProvider\SettingFormDataProvider
        arguments:
            - '@drsoft_fr.module.validate_customer_pro.data.configuration.setting_configuration'

    drsoft_fr.module.validate_customer_pro.form.choice_provider.setting_choice_provider:
        class: DrSoftFr\Module\ValidateCustomerPro\Form\ChoiceProvider\SettingChoiceProvider
        arguments:
            - '@drsoft_fr.module.validate_customer_pro.data.form_fields_data_provider'
            - '@prestashop.adapter.data_provider.group'
            - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
            - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

    drsoft_fr.module.validate_customer_pro.form.handler.setting_form_handler:
        class: PrestaShop\PrestaShop\Core\Form\Handler
        arguments:
            - '@form.factory'
            - '@prestashop.core.hook.dispatcher'
            - '@drsoft_fr.module.validate_customer_pro.form.data_provider.setting_form_data_provider'
            - DrSoftFr\Module\ValidateCustomerPro\Form\SettingType
            - 'DrSoftFrModuleValidateCustomerProSetting'
        public: true

    # setting form
    drsoft_fr.module.validate_customer_pro.form.setting_type:
        class: DrSoftFr\Module\ValidateCustomerPro\Form\SettingType
        parent: 'form.type.translatable.aware'
        arguments:
            - '@=service("prestashop.adapter.data_provider.cms").getCmsChoices()'
            - '@=service("drsoft_fr.module.validate_customer_pro.form.choice_provider.setting_choice_provider").getFormFieldChoices()'
            - '@=service("drsoft_fr.module.validate_customer_pro.form.choice_provider.setting_choice_provider").getGroupChoices()'
        tags:
            - { name: form.type }
