services:
    # Data validator
    drsoft_fr.module.validate_customer_pro.data.validator.setting_validator:
        class: DrSoftFr\Module\ValidateCustomerPro\Data\Validator\SettingValidator
        arguments:
            - '@drsoft_fr.module.validate_customer_pro.adapter.query_handler.cms_page.get_id_cms_pages_provider'
            - '@drsoft_fr.module.validate_customer_pro.data.provider.form_fields_provider'
            - '@drsoft_fr.module.validate_customer_pro.adapter.query_handler.group.get_id_groups_provider'

    # Data factory
    drsoft_fr.module.validate_customer_pro.data.factory.setting_data_factory:
        class: DrSoftFr\Module\ValidateCustomerPro\Data\Factory\SettingDataFactory
        arguments:
            - '@drsoft_fr.module.validate_customer_pro.data.configuration.setting_configuration'

    # Data provider
    drsoft_fr.module.validate_customer_pro.data.configuration.setting_configuration:
        class: DrSoftFr\Module\ValidateCustomerPro\Data\Configuration\SettingConfiguration
        arguments:
            - '@prestashop.adapter.legacy.configuration'
            - '@drsoft_fr.module.validate_customer_pro.data.validator.setting_validator'
        public: true

    drsoft_fr.module.validate_customer_pro.data.setting_data_provider:
        class: DrSoftFr\Module\ValidateCustomerPro\Data\Factory\SettingDataFactory
        factory: 'drsoft_fr.module.validate_customer_pro.data.factory.setting_data_factory:getData'
        public: true
