services:
    # Query services
    drsoft_fr.module.validate_customer_pro.query.customer.get_id_customers_query:
        class: DrSoftFr\Module\ValidateCustomerPro\Query\Customer\GetIdCustomersQuery
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getContext().shop.id'

    # Query handler services
    drsoft_fr.module.validate_customer_pro.adapter.query_handler.customer.get_id_customers_query_handler:
        class: DrSoftFr\Module\ValidateCustomerPro\Adapter\QueryHandler\Customer\GetIdCustomersQueryHandler
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'

    # Provider
    drsoft_fr.module.validate_customer_pro.adapter.query_handler.customer.get_id_customers_provider:
        class: DrSoftFr\Module\ValidateCustomerPro\Adapter\QueryHandler\Customer\GetIdCustomersQueryHandler
        factory: 'drsoft_fr.module.validate_customer_pro.adapter.query_handler.customer.get_id_customers_query_handler:handle'
        arguments:
            - '@drsoft_fr.module.validate_customer_pro.query.customer.get_id_customers_query'
        public: true

    # repository
    drsoft_fr.module.validate_customer_pro.repository.adapter_customer_repository:
        class: DrSoftFr\Module\ValidateCustomerPro\Repository\AdapterCustomerRepository
        factory: [ '@doctrine.orm.default_entity_manager', getRepository ]
        arguments:
            - DrSoftFr\Module\ValidateCustomerPro\Entity\AdapterCustomer
        public: true
